const Products = {
  productInfo: [
    {
      productCode: '001',
      productName: 'Black Opium',
      productDesc: 'Similar to the well known perfume. Floral with notes of black coffee, white florals and vanilla.',
      productVariation: ['Snap Bar', 'Individuals', 'Sample'],
      scentType: 'perfume',
      image: 'BlackOpium.jpg',
    },
    {
      productCode: '002',
      productName: 'Spring Awakening',
      productDesc: 'Similar to the popular fabric conditioner. Spring flowers, with hints of Patchouli and White Cedar.',
      productVariation: ['Snap Bar', 'Individuals', 'Sample'],
      scentType: 'cleaning',
      image: 'springAwakening.jpg',
    },
    {
      productCode: '003',
      productName: 'English Pear & Freesia',
      productDesc: 'Similar in notes and identity to the popular scent. Pear, Quince, White Freesia and Wild Rose, Rhubarb, Patchouli, Amber and White Musk.',
      productVariation: ['Snap Bar', 'Individuals', 'Sample'],
      scentType: 'perfume',
      image: 'EnglishPearFreesia.jpg',
    },
    {
      productCode: '004',
      productName: 'Lime Basil & Mandarin',
      productDesc: ' Similar in notes and identity to the popular scent. Pepper, Basil, White Thyme and Sweet Lime.',
      productVariation: ['Snap Bar', 'Individuals', 'Sample'],
      scentType: 'perfume',
      image: 'limeBasil&Mandarin.jpg',
    },
    {
      productCode: '005',
      productName: 'Peony & Blush Suede',
      productDesc: 'Similar in notes and identity to the popular scent.  Peonies, Red apple, Jasmine, Rose, Gillyflower, Carnation, Rose, Suede.',
      productVariation: ['Snap Bar', 'Individuals', 'Sample'],
      scentType: 'perfume',
      image: 'Peony&Blush.jpg',
    },
    {
      productCode: '006',
      productName: 'Baby Powder',
      productDesc: 'Just like the classic baby powder scent we all love. A sweet and memorable smell of clean elegance.',
      productVariation: ['Snap Bar', 'Individuals', 'Sample'],
      scentType: 'other',
      image: 'BabyPowder.jpg',
    },
    {
      productCode: '007',
      productName: 'Twilight Garden',
      productDesc: 'Similar to the popular fragranced cleaner. Lilies, Ylang and Jasmine, Peach and Musk.',
      productVariation: ['Snap Bar', 'Individuals', 'Sample'],
      scentType: 'cleaning',
      image: 'twilightGarden.jpg',
    },
    {
      productCode: '008',
      productName: 'Mountain Air',
      productDesc: 'Similar to the popular fragranced cleaner. Notes of Lime, Pineapple, Parmma Violet, Lavender, Gardenia, Rose, Iris, Lily and Heliotrope, Orange Blossom, Precious Wood & Amber.',
      productVariation: ['Snap Bar', 'Individuals', 'Sample'],
      scentType: 'cleaning',
      image: 'MountainAir.jpg',
    },
    {
      productCode: '009',
      productName: 'Fresh Linen',
      productDesc: 'Similar to the popular fragranced cleaner. Light, Airy and Clean.',
      productVariation: ['Snap Bar', 'Individuals', 'Sample'],
      scentType: 'cleaning',
      image: 'freshLinen.jpg',
    },
    {
      productCode: '010',
      productName: 'Springtime',
      productDesc: 'Similar to the popular fragranced cleaner A combination of freshly cut green leaves and herbs, blossoming of new spring flowers.',
      productVariation: ['Snap Bar', 'Individuals', 'Sample'],
      scentType: 'cleaning',
      image: 'Springtime.jpg',
    },
    {
      productCode: '011',
      productName: 'Madam Coco',
      productDesc: "Similar to the iconic Ladies' perfume. Notes of Orange, Jasmine, Rose, Patchouli and Vetiver.",
      productVariation: ['Snap Bar', 'Individuals', 'Sample'],
      scentType: 'perfume',
      image: 'MadamCoco.jpg',
    },
    {
      productCode: '012',
      productName: 'Lady Millionaire',
      productDesc: "Similar to the popular women's perfume. Fresh notes of patchouoli and florals.",
      productVariation: ['Snap Bar', 'Individuals', 'Sample'],
      scentType: 'perfume',
      image: 'LadyMillionaire.jpg',
    },
    {
      productCode: '013',
      productName: 'Sage & Sea Salt',
      productDesc: "Similar in notes and identity to the popular scent. Sage & Sea Salt Think breaking waves, salty air sandy beaches mixed with earthy sage.",
      productVariation: ['Snap Bar', 'Individuals', 'Sample'],
      scentType: 'perfume',
      image: 'Sage&SeaSalt.jpg',
    },
    {
      productCode: '014',
      productName: 'Country Garden',
      productDesc: "Similar to the popular fragranced cleaner. Hyacinth, Violet Leaf and English Rhubarb, Rose and Musk.",
      productVariation: ['Snap Bar', 'Individuals', 'Sample'],
      scentType: 'cleaning',
      image: 'CountryGarden.jpg',
    },
    {
      productCode: '015',
      productName: 'La Vie Est Belle',
      productDesc: "Similar to the iconic women's fragrance. Iris Pallida, Jasmin Sambac Absolute, Orange Blossom Absolute, Patchouli Essence.",
      productVariation: ['Snap Bar', 'Individuals', 'Sample'],
      scentType: 'perfume',
      image: 'LaVieEstBelle.jpg',
    },
    {
      productCode: '016',
      productName: 'Kir Royale',
      productDesc: "Green fig, Red Berries, Cassis,Oorchard Apples,  Lily Blossom, Pink Rose, Jasmine,. All tied together with a note of Vanilla.",
      productVariation: ['Snap Bar', 'Individuals', 'Sample'],
      scentType: 'other',
      image: 'KirRoyale.jpg',
    },
    {
      productCode: '017',
      productName: 'Alien Invasion',
      productDesc: "Similar to the women’s fragrance. Woody Amber, Jasmine Sambac, Cashmeran Wood and White Amber.",
      productVariation: ['Snap Bar', 'Individuals', 'Sample'],
      scentType: 'perfume',
      image: 'AlienInvasion.jpg',
    },

  ],
  pricing: [
    {
      snapBar: '450',
      individual: '350',
      sample: '100',
      giftBox: '1500',
    }
  ]
}

export default Products;